config/routes.rb
WorkRails1::Application.routes.draw do


	post 'validation_ajax' => 'public/users#validation_ajax'
	post 'validation_aj' => 'public/users#validation_ajax'
	post 'public/users/validation_ajax'
	post 'public/users/validation_aj' => 'public/users#validation_ajax'
	post 'public/validation_aj'=> 'public/users#validation_ajax'
	post 'public/validation_ajax'=> 'public/users#validation_ajax'


	post 'sort_bd' => 'admin/administrators#sort'
	post 'admin/sort_bd' =>'admin/administrators#sort'


  root :to => "public/users#index"

	scope "public" do
  	get '/' => 'public/users#index'
		resources :users, controller:"public/users"
		resources :sessions, controller:"public/sessions"

		resources :recover_password, controller:"public/recover_password"

		resources :pictures, controller:"public/pictures"
	end

	namespace :admin do 
		get '/' => 'administrators#index'
		resources :administrators
		get 'edit_me' => 'administrators#edit_me'
		post 'update_me' => 'administrators#update_me'
		resources :sessions
	end

	namespace :superadmin do
		resources :sadmin
	end

	
end

app/controllers/admin/administrators_controller.rb
# -*- coding: utf-8 -*-
class Admin::AdministratorsController < ApplicationController
  include Edit_User_Position
	before_filter :find_user, only: [:edit, :update, :destroy]
  before_filter :current_admin?, only: [:edit_me,:update_me]
  before_filter :current_admin_id

  load_and_authorize_resource :user, except:[:show,:edit_me,:update_me], :parent => false

  def index

    if can? :manage, Admin
      redirect_to superadmin_sadmin_index_url
    else

      @users = all_user
  
    end

  end

  def show
    if params[:id]

     @sort=params[:id].split(',')

     @users=User.order("#{@sort[0]} #{@sort[1]}").paginate(:page => params[:page])

    end
  end

  def edit

  end

  def update
    @user.update_attributes(person_params)
    @users=all_user

     respond_to do |format|
      if @user.errors.empty?

         format.js{@rezult=true}
         format.html{redirect_to admin_url}
      else

         format.js{@rezult=false}
         format.html{render "edit"}
      end
     end
  end


  def destroy

    @users=all_user
    @user.destroy

  end

  def sort
    @params=params['param1']

    edit_user_position(@params)

  end

  def edit_me
    @admin=Admin.find(current_admin.id)
  end

  def update_me
     @admin=Admin.find(current_admin.id)
     @admin.update_attributes(person_params_admin)
  end

  private
    def find_user
      @user = User.find(params[:id])
    end

    def all_user
      User.order("position ASC").paginate(:page => params[:page])
    end

    def person_params
      params.require(:user).permit(:last_name,:first_name,
  :email,:password,:information,:password_confirmation)
    end

    def person_params_admin
      params.require(:admin).permit(:last_name,:first_name,
  :email,:information)
    end

    def current_admin?
       authorize
    end

    def current_admin_id
      @admin=current_admin
    end


end

app/helpers/admin/administrators_helper.rb
module Admin::AdministratorsHelper
end

app/views/admin/administrators/destroy.js.erb
$("#admin_all_").html('<%=j render 'admin/partial/users_all_ajax' %>');

app/views/admin/administrators/edit.html.erb
<h1>Edit User</h1>

<%= render partial: "admin/partial/edit" %>

app/views/admin/administrators/edit.js.erb
$("#admin_all_").html('<%=j render 'admin/partial/edit' %>');

app/views/admin/administrators/edit_me.js.erb
$("#edit_me").html('<%=j render 'admin/partial/form_admin' %>');

app/views/admin/administrators/index.html.erb
<div id="user_nav">
	<% content_for :head do %>
		 Logged in as <%= current_admin.email %>

		<%= link_to("Log out",  admin_session_url(session[:admin_id]), method: :delete) %>
<% end %>
		<div id="admin_all_">
		<%= render partial: "admin/partial/users_all_ajax" %>
		</div>
		<br>

		<%#= ajax_will_paginate @users, :params => { :my_excluded_param => nil } %>

		<%#= will_paginate @users%>


</div>

app/views/admin/administrators/index.js.erb
$("#admin_all_").html('<%=j render 'admin/partial/users_all_ajax' %>');

app/views/admin/administrators/show.js.erb
$("#sortable").html('<%=j render 'admin/partial/sort' %>');

id="#<%=@sort[0]%>_title";

if ($(id).attr('title')=='up'){

	<% s="#{@sort[0]},DESC" %>
$(id).attr("href","<%= admin_administrator_url(s) %>");
$(id).attr('title','down');
}else
{
<% s="#{@sort[0]},ASC" %>
$(id).attr("href","<%= admin_administrator_url(s) %>");
$(id).attr('title','up');
}

app/views/admin/administrators/sort.js.erb
function checkTime(i)
{
	if (i<10)
	{
		i="0" + i;
	}
	return i;
}

var t = new Date();

<% if @params.first.split('_')[3] != 'position' %>

$("#sort_view").html('Select referens position and move element for save bd')

<% else %>

$("#sort_view").html("Update position in "+checkTime(t.getHours())+"."+checkTime(t.getMinutes())+"."+checkTime(t.getSeconds()))

<% end %>

app/views/admin/administrators/update.js.erb
<% if @rezult==true %>
$("#admin_all_").html('<%=j render 'admin/partial/users_all_ajax' %>');

<% else %>
$("#admin_all_").html('<%=j render 'admin/partial/edit' %>');

<% end %>

app/views/admin/administrators/update_me.js.erb
<% if @admin.errors.empty? %>




$("#edit_me").html('<%=j render 'admin/partial/edit_admin' %>');

 
    
<% else %>
$("#edit_me").html('<%=j render 'admin/partial/form_admin' %>');
<% end %>