config/routes.rb
WorkRails1::Application.routes.draw do


	post 'validation_ajax' => 'public/users#validation_ajax'
	post 'validation_aj' => 'public/users#validation_ajax'
	post 'public/users/validation_ajax'
	post 'public/users/validation_aj' => 'public/users#validation_ajax'
	post 'public/validation_aj'=> 'public/users#validation_ajax'
	post 'public/validation_ajax'=> 'public/users#validation_ajax'


	post 'sort_bd' => 'admin/administrators#sort'
	post 'admin/sort_bd' =>'admin/administrators#sort'


  root :to => "public/users#index"

	scope "public" do
  	get '/' => 'public/users#index'
		resources :users, controller:"public/users"
		resources :sessions, controller:"public/sessions"

		resources :recover_password, controller:"public/recover_password"

		resources :pictures, controller:"public/pictures"
	end

	namespace :admin do 
		get '/' => 'administrators#index'
		resources :administrators
		get 'edit_me' => 'administrators#edit_me'
		post 'update_me' => 'administrators#update_me'
		resources :sessions
	end

	namespace :superadmin do
		resources :sadmin
	end

	
end

app/views/admin/partial/_edit.html.erb
<h2> Edit user </h2>

<%= render partial: "admin/partial/errors" %>

<%= form_for @user, url: admin_administrator_url, remote: true do |f| %>

  <p>

    <%= f.text_field :email,class: "input-block-level", placeholder:"Email"  %>
    </p>
  <p>
    <%= f.text_field :first_name,class: "input-block-level", placeholder:"First name" %>
    </p>

  <p>
    <%= f.text_field :last_name,class: "input-block-level", placeholder:"Last name" %>
    </p>

  <p>
    <%= f.text_area :information,class: "input-block-level", placeholder:"Other information",  rows:'3' %></p>


   <%= f.submit class:"btn btn-primary" %>

   <%= link_to "Cancel", admin_url, remote: true, class:"btn btn-primary" %>

<% end %>

app/views/admin/partial/_edit_admin.html.erb
<%= link_to('Edit you information',  admin_edit_me_url, remote: true) %>
<br/>
Email: <span class='small'><%= @admin.email %></span>
<br/>
First name: <span class='small'><%= @admin.first_name %></span>
<br/>
Last name: <span class='small'><%= @admin.last_name %></span>
<br/>
Information: <span class='small'><%= @admin.information %></span>

app/views/admin/partial/_errors.html.erb
 <div class="error_messages">
 <% if @user.errors.any? %>

        <% for message in @user.errors.full_messages %>
         <%= message %><br/>
        <% end %>

  <% end %>
</div>

app/views/admin/partial/_form_admin.html.erb
<% if @admin.errors.any? %>
<div class='error_messages'>
  <%for message in @admin.errors.full_messages%><%=message%>
  <br>
  <%end%>
</div>
  <% end %>
</div>

<%= form_for @admin,  url: admin_update_me_url, method: :post, remote: true do |f| %>

  <p>
    <%= f.text_field :email,class: "input-block-level", placeholder:"Email"  %>
    </p>
  <p>
    <%= f.text_field :first_name,class: "input-block-level", placeholder:"First name" %>
    </p>

  <p>
    <%= f.text_field :last_name,class: "input-block-level", placeholder:"Last name" %>
    </p>

  <p>
    <%= f.text_area :information, size: "30x3",class: "input-block-level", placeholder:"information" %></p>

   <%= f.submit class:"btn btn-primary" %>

   <%= link_to "Cancel", admin_url, class:"btn btn-primary", remote: true %>

<% end %>

app/views/admin/partial/_form_user.html.erb
<%= render partial: "admin/partial/errors" %>

<%= form_for @user, url: admin_administrators_url  do |f| %>

  <p>

    <%= f.label :email %><br />
    <%= f.text_field :email  %>
    </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
    </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
    </p>

  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
    </p>

  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
    </p>

  <p>
    <%= f.label :information %><br />
    <%= f.text_area :information, size: "30x3" %></p>


   <%= f.submit class:"btn btn-primary" %>

   <%= link_to "Cancel", admin_url, class:"btn btn-primary" %>

<% end %>

app/views/admin/partial/_sort.html.erb
<%= javascript_include_tag "sortable" %>

<% if !@sort
	@sort=[]
  @sort[0]='position'
  @sort[1]='ASC'
	end %>

<% @users.each do |key| %>

<li class="ui-state-default" id="li_<%= key[:id] %>_<%= key[:position] %>_<%= @sort[0] %>_<%= @sort[1] %>">


<span class='name'>
 <%= link_to(key[:email], edit_admin_administrator_url(key[:id]), remote: true) %>
</span>

<span class='name'>
<%= key[:last_name] %>
</span>

<span class='name'>
<%= key[:first_name] %>
</span>

<span class='name'>
<%= link_to("delete! -> #{key[:position]}", admin_administrator_url(key[:id]), method: :delete, remote: true) %>
</span>



</li>
<% end %>
<%= ajax_will_paginate @users, :params => { :my_excluded_param => nil } %>
<%#= will_paginate @users %>

app/views/admin/partial/_users_all_ajax.html.erb
<% if @users.empty? %>
<div id='sort_view'>bd Users empty</div>
<% else %>

<h2> Users </h2>

<div class="btn-group">
  <a class="btn btn-inverse" data-toggle="dropdown" href="#">
    Sort items, up and down
    <span class="caret"></span>
  </a>

<ul class="dropdown-menu">
<li class='title'>

<%= link_to 'Email', admin_administrator_url('email,ASC'), id:'email_title',title:'up',remote: true %>
</li>

<li class='title'>

<%= link_to 'Last name', admin_administrator_url('last_name,ASC'), id:'last_name_title', title:'up', remote: true %>

</li>
<li class='title'>

<%= link_to 'First name', admin_administrator_url('first_name,ASC'), id:'first_name_title',title:'up', remote: true %>

</li>
<li class='title'>
<%= link_to 'Position', admin_administrator_url('position,ASC'), id:'position_title',title:'up', remote: true %>
</li>
</ul>
</div>


<ul class='header_ul'>
<li>

<span class='name'>
Email
</span>

<span class='name'>
Last name
</span>

<span class='name'>
First name
</span>

<span class='name'>
Position
</span>

</li>
</ul>



<ul id="sortable" >

<%= render partial: "admin/partial/sort" %>

</ul>


<div id='sort_view'>Select element for move</div>
<% end %>


<br/>
<div id='edit_me'>
<%= render partial: "admin/partial/edit_admin" %>
</div>
<br>

<br>
<%= render partial: "public/partial/upload_pictures" %>