config/routes.rb
WorkRails1::Application.routes.draw do


	post 'validation_ajax' => 'public/users#validation_ajax'
	post 'validation_aj' => 'public/users#validation_ajax'
	post 'public/users/validation_ajax'
	post 'public/users/validation_aj' => 'public/users#validation_ajax'
	post 'public/validation_aj'=> 'public/users#validation_ajax'
	post 'public/validation_ajax'=> 'public/users#validation_ajax'


	post 'sort_bd' => 'admin/administrators#sort'
	post 'admin/sort_bd' =>'admin/administrators#sort'


  root :to => "public/users#index"

	scope "public" do
  	get '/' => 'public/users#index'
		resources :users, controller:"public/users"
		resources :sessions, controller:"public/sessions"

		resources :recover_password, controller:"public/recover_password"

		resources :pictures, controller:"public/pictures"
	end

	namespace :admin do 
		get '/' => 'administrators#index'
		resources :administrators
		get 'edit_me' => 'administrators#edit_me'
		post 'update_me' => 'administrators#update_me'
		resources :sessions
	end

	namespace :superadmin do
		resources :sadmin
	end

	
end

app/controllers/superadmin/sadmin_controller.rb
# -*- coding: utf-8 -*-
class Superadmin::SadminController < ApplicationController
	before_filter :find_user, only: [:edit, :update, :destroy]
	load_and_authorize_resource :admin, :parent => false

	def index
		
		#@admins = Admin.all(:include => :role, :conditions => { :roles => { :name => 'admin'} })

		@admins= Admin.includes(:role).where('roles.name != ?', 'super_admin')

	end

	def new
		@user = Admin.new
	end

	def show
	end

	def create
		@user = Admin.new(resource_params)

		@user.role=Role.where(name:'admin').first

		#@user.role=r[:id]

     if @user.save

       redirect_to superadmin_sadmin_index_url, :notice => "Signed up!"

     else
       render "new"
     end
	end

	def edit

	end

	def update
    @user.update_attributes(resource_params)
    
      if @user.errors.empty?        
      	redirect_to superadmin_sadmin_index_url
      else
        render "edit"
      end
  end

	def destroy
    @user.delete
    redirect_to superadmin_sadmin_index_url
  end

  private
    def find_user
      @user = Admin.find(params[:id])
    end

    def resource_params
    	params.require(:admin).permit(:last_name,:first_name,
  :email,:password,:information,:password_confirmation)
		end
end

app/helpers/superadmin/sadmin_helper.rb
module Superadmin::SadminHelper
end

app/views/superadmin/partial/_edit.html.erb
<%= form_for @user, url: superadmin_sadmin_url  do |f| %>

  <p>

    <%= f.text_field :email, class: "input-block-level", placeholder:"Email"  %>
    </p>
  <p>
    <%= f.text_field :first_name, class: "input-block-level", placeholder:"First name" %>
    </p>

  <p>

    <%= f.text_field :last_name, class: "input-block-level", placeholder:"Last name" %>
    </p>

  <p>

    <%= f.text_area :information, size: "30x3", class: "input-block-level", placeholder:"Information" %></p>


   <%= f.submit class:"btn btn-primary" %>

   <%= link_to "Cancel", superadmin_sadmin_index_url, class:"btn btn-primary" %>

<% end %>

app/views/superadmin/partial/_errors.html.erb
 <div class="error_messages">
 <% if my_error.errors.any? %>

        <% for message in my_error.errors.full_messages %>
         <%= message %><br/>
        <% end %>

  <% end %>
</div>

app/views/superadmin/partial/_form_user.html.erb
<%= form_for @user, url: superadmin_sadmin_index_url  do |f| %>

  <p>

    <%= f.text_field :email, class: "input-block-level", placeholder:"Email"  %>
    </p>
  <p>
    <%= f.password_field :password, class: "input-block-level", placeholder:"Password" %>
    </p>
  <p>
    <%= f.password_field :password_confirmation, class: "input-block-level", placeholder:"Password confirmation" %>
    </p>

  <p>
    <%= f.text_field :first_name, class: "input-block-level", placeholder:"First name" %>
    </p>

  <p>
    <%= f.text_field :last_name, class: "input-block-level", placeholder:"Last name" %>
    </p>

  <p>
    <%= f.text_area :information, size: "30x3", class: "input-block-level", placeholder:"Information" %></p>


   <%= f.submit class:"btn btn-primary" %>

   <%= link_to "Cancel", superadmin_sadmin_index_url, class:"btn btn-primary" %>

<% end %>

app/views/superadmin/partial/_users_all.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Admins</div>
<table class="table table-striped">
<tr>
<td class='title'>
Email
</td>
<td class='title'>
Last name
</td>
<td class='title'>
First name
</td>
<td class='title'>
Delete
</td>
</tr>


<% 
	@admins.each do |key|

		concat raw "<tr><td> #{ link_to(key[:email],  edit_superadmin_sadmin_url(key[:id])) } </td>
		<td> #{key[:last_name]} </td>
		<td> #{key[:first_name]} </td>
		<td>
		#{ link_to("X", superadmin_sadmin_url(key[:id]), method: :delete) }
		</td>
		</tr>"

	end 
%>

</table>
</div>