config/routes.rb
WorkRails1::Application.routes.draw do


	post 'validation_ajax' => 'public/users#validation_ajax'
	post 'validation_aj' => 'public/users#validation_ajax'
	post 'public/users/validation_ajax'
	post 'public/users/validation_aj' => 'public/users#validation_ajax'
	post 'public/validation_aj'=> 'public/users#validation_ajax'
	post 'public/validation_ajax'=> 'public/users#validation_ajax'


	post 'sort_bd' => 'admin/administrators#sort'
	post 'admin/sort_bd' =>'admin/administrators#sort'


  root :to => "public/users#index"

	scope "public" do
  	get '/' => 'public/users#index'
		resources :users, controller:"public/users"
		resources :sessions, controller:"public/sessions"

		resources :recover_password, controller:"public/recover_password"

		resources :pictures, controller:"public/pictures"
	end

	namespace :admin do 
		get '/' => 'administrators#index'
		resources :administrators
		get 'edit_me' => 'administrators#edit_me'
		post 'update_me' => 'administrators#update_me'
		resources :sessions
	end

	namespace :superadmin do
		resources :sadmin
	end

	
end

app/controllers/superadmin/sadmin_controller.rb
# -*- coding: utf-8 -*-
class Superadmin::SadminController < ApplicationController
	before_filter :find_user, only: [:edit, :update, :destroy]
	load_and_authorize_resource :admin, :parent => false

	def index
		
		#@admins = Admin.all(:include => :role, :conditions => { :roles => { :name => 'admin'} })

		@admins= Admin.includes(:role).where('roles.name != ?', 'super_admin')

	end

	def new
		@user = Admin.new
	end

	def show
	end

	def create
		@user = Admin.new(resource_params)

		@user.role=Role.where(name:'admin').first

		#@user.role=r[:id]

     if @user.save

       redirect_to superadmin_sadmin_index_url, :notice => "Signed up!"

     else
       render "new"
     end
	end

	def edit

	end

	def update
    @user.update_attributes(resource_params)
    
      if @user.errors.empty?        
      	redirect_to superadmin_sadmin_index_url
      else
        render "edit"
      end
  end

	def destroy
    @user.delete
    redirect_to superadmin_sadmin_index_url
  end

  private
    def find_user
      @user = Admin.find(params[:id])
    end

    def resource_params
    	params.require(:admin).permit(:last_name,:first_name,
  :email,:password,:information,:password_confirmation)
		end
end

app/helpers/superadmin/sadmin_helper.rb
module Superadmin::SadminHelper
end

app/views/superadmin/sadmin/edit.html.erb
<h2>Edit</h2>

 <% 
  content_for :head do
  concat('Logged in as super_admin ')

  concat(link_to("Log out",  admin_session_url(session[:admin_id]), method: :delete)) 
  end %>

<%= render partial: "superadmin/partial/errors", locals: {my_error: @user} %>

<%= render partial: "superadmin/partial/edit" %>

app/views/superadmin/sadmin/index.html.erb
<div id="user_nav">
  <% 
  content_for :head do
  concat('Logged in as super_admin ')

  concat(link_to("Log out",  admin_session_url(session[:admin_id]), method: :delete)) 
  end %>

 	<%= render partial: "superadmin/partial/users_all" %>
 	<%= link_to "Add Admin", new_superadmin_sadmin_url, class:"btn btn-primary" %>

</div>

app/views/superadmin/sadmin/new.html.erb
<h2>Sign Up</h2>

 <% 
  content_for :head do
  concat('Logged in as super_admin ')

  concat(link_to("Log out",  admin_session_url(session[:admin_id]), method: :delete)) 
  end %>

<%= render partial: "superadmin/partial/errors", locals: {my_error: @user} %>

<%= render partial: "superadmin/partial/form_user" %>